### ISSUE TITLE
Bracketeer JDT doesn't work when GWT is enabled for the project

### ISSUE THREAD

**Issue by golimpio** [chookapp/Bracketeer#1]
It doesn't work when using Google Web Toolkit for the project.

**Comment by chookapp** [comment]
The next version of Bracketeer would support GWT (specifically the "Window Builder").
Is there another kind of "Editor" (other than the Window Builder) you use, and is not supported?

**Comment by markerikson** [comment]
Just installed Bracketeer JDT, and noticed that it works for the standard JDT Java editor, but not the GWT Java Editor.  If you could make it work for the GWT Java editor too, that would be extremely useful.  Thanks!

**Comment by chookapp** [comment]
The fix is already implemented in the upcoming version of Bracketeer. Hopefully, I'll release it within a couple of weeks.
