### ISSUE TITLE
Hints fore case and if ... else ...

### ISSUE THREAD

**Issue by mumpitzstuff** [chookapp/Bracketeer#3]
It would be nice to have the hint feature for cases (switch) and for if ... else ... constructs in C.

**Comment by chookapp** [comment]
Could you, please, give an example of where you would expect the "hint" to be for "case" statements? I thought of this a while ago and didn't come up with a good place to put it.

Also, Bracketeer already has a hint for "if" and "else" in C. So I'm not sure I understand...

**Comment by mumpitzstuff** [comment]
It seems that statements like

if (...)
{
  ...
}
else
{
  ...
}

are not recognized by your hint algorithm. It may be a bug?

Our case statements have always this format:

switch (...)
{
  case 1:
  {
    ...
  } <hint should be visible>
  default:
  {
    ...
  } <hint should be visible>
} <hint is already visible>

But i agree there are many possibilities to write C code. Another format could be:

switch (...)
{
  case 1:
    ...   <no break no hint (such constructs are to dangerous to use in my opinion)>
  case 2:
    ...
    break; <hint could be visible here>
  default:
    ...
    break; <hint could be visible here>
} <hint is already visible>

**Comment by mumpitzstuff** [comment]
Hmm sry some parts of my comment are removed. 

case 1:
{

}

This should be easy to add to your hint algorithm.

For the last example use the breaks to add the hint. The case without break is a really dangerous thing in my opinion and should not be used. Therefore it is a rare case and it is not needed to add a hint here.

**Comment by chookapp** [comment]
Nice idea, I will consider it for the next Bracketeer version

**Comment by chookapp** [comment]
Done
