### ISSUE TITLE
Preprocessor "Multiline" Hints 

### ISSUE THREAD

**Issue by tobiasd123** [chookapp/Bracketeer#6]
Hi, 

we use a lot of Preprocessor encapsulations with quite complex conditions. 
The ease the readability we use the line continuation with "\".

In the following example:
...
# if (    ( MACRO_A == 1) \

```
     && ( MARCO_B == 1) \
)
// Code A
```
# else

```
// Code B
```
# endif

// Code C
...
the displayed hints overlap with the code B and C. 
Which is not very readable.
Could you limit the displayed hints to one line?

Apart from this Bracketeer is my PlugIn of the Month. 
Thanks a lot
Tobi

**Comment by chookapp** [comment]
Thanks, in all my tests, I never tested a multi-line condition.
Will be fixed in the upcoming version.
