### ISSUE TITLE
bad hot keys

### ISSUE THREAD

**Issue by flreinhard** [chookapp/Bracketeer#7]
Hi!

the default hot-key assignment for bracketeer includes ctrl+b which is "Build all" on a default CDT.

In window->preferences->general->keys i couldn't find the key assignments bracketeer uses.

Since i'm heavily used to ctrl-b for "build", how can i remove the bracketeer key assignments?

Thx for the great plugin!

**Comment by flreinhard** [comment]
Classic pebkac, found it and removed it, anyways, ctrl-b shouldn't be used by default on cdt, dont't know about jdt

**Comment by chookapp** [comment]
Agreed, any suggestions to an alternative hot key?
