### ISSUE TITLE
Allways warns

### ISSUE THREAD

**Issue by mandmss** [chookapp/Bracketeer#8]
The Bracketeer plugin is continuously (cca 30 / sec) writing warnings in the Eclipse Error log such this:

!ENTRY com.chookapp.org.Braketeer 2 0 2012-09-24 12:48:15.308
!MESSAGE 
!STACK 0
java.lang.IllegalStateException
    at org.eclipse.jdt.core.dom.ASTParser.internalCreateAST(ASTParser.java:1122)
    at org.eclipse.jdt.core.dom.ASTParser.createAST(ASTParser.java:807)
    at com.chookapp.org.bracketeer.jdt.BracketeerJdtProcessor.processAst(BracketeerJdtProcessor.java:88)
    at com.chookapp.org.bracketeer.jdt.BracketeerJdtProcessor.processDocument(BracketeerJdtProcessor.java:69)
    at com.chookapp.org.bracketeer.extensionpoint.BracketeerProcessor.process(BracketeerProcessor.java:47)
    at com.chookapp.org.bracketeer.core.ProcessingThread.run(ProcessingThread.java:81)
    at java.lang.Thread.run(Thread.java:662)

**Comment by chookapp** [comment]
Thank you for informing me of this issue... I will look into it.
BTW, do you suspect anything specific in your environment causing this issue (when editing a specific file, for example)?

**Comment by FraGag** [comment]
I'm having this issue as well.

It seems to start when I open a .class file with no source attached; in that case the editor is not a Java source code editor, but rather a disassembly of the Java byte code in a text box. What's really annoying is that it doesn't stop after I close that editor; warnings keep getting added to the error log every half second or so.

Also, when I open a .class file that **does** have source code available, an error is added to the error log: `Unable to get resource` (`An exception stack trace is not available.`). This error is added only once after opening a file, but more errors like that will be added if I open other .class files with source.

I'm using Eclipse Juno 4.2.

**Comment by FraGag** [comment]
For the record, attaching a source jar from an editor that shows the `No source available` message and the byte code disassembly causes the warnings to stop for that editor (and causes the `Unable to get resource` mentioned in my previous comment to be added to the log).

**Comment by chookapp** [comment]
Fixed in upcoming version (1.3.0)
1. A class with no source will not show any warning of "Unable to get resource" (whether it has a source attached or not).
2. Fixed also the underlying problem of errors persisting after closing the editor.

**Comment by zkendall** [comment]
Release 1.3!!!

**Comment by srufle** [comment]
1.3 does not look like it is in the Update site
http://chookapp.github.com/ChookappUpdateSite/

**Comment by mgsCatDev** [comment]
2019 and still Update Site is outdated...
This plugin could be a "must have plugin" but unacceptable with the behaviour showed in this issue.
